/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package erp;

import java.awt.CardLayout;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.ListUI;
import javax.swing.table.DefaultTableModel;
import sun.awt.VariableGridLayout;

/**
 *
 * @author Prudhvi
 */
public class SemRegisPanel extends javax.swing.JPanel {

    /**
     * Creates new form SemRegisPanel
     */
    List<Course> coreCoursesList,electiveCoursesList;
    DefaultListModel listModel;
    JList jList;
    int numofElectives;
    public SemRegisPanel() {
        initComponents();
         listModel=new DefaultListModel();
         jList=new JList(listModel);
        ListPanel.add(jList);
        jList.setFixedCellWidth(500);
        jList.setFont(jList.getFont().deriveFont(20.0f));
        jList.addMouseListener(mouseListener);
    }
    public void init(Student x)
    {
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        electivesLabel = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        ListPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 204, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 2, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Semester Registration");

        electivesLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        electivesLabel.setText("Select Electives");

        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        NameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NameLabel.setText("jLabel3");

        TextArea.setColumns(20);
        TextArea.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        TextArea.setRows(5);
        TextArea.setText("Course Name\t\tCourse Code\t\tCredits\t\tCore/Elective\n");
        jScrollPane2.setViewportView(TextArea);

        ListPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(RegisterButton)
                        .addGap(92, 92, 92)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
                            .addComponent(ListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(electivesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(electivesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(ListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterButton)
                    .addComponent(jButton2))
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
         //clearing the previous ones
        
        Student x=RegisterPanel.loggedinStudent;
        NameLabel.setText(x.getName());
       
       
        
        coreCoursesList=StudentExt.getCoreCourses(x,1);
        electiveCoursesList=StudentExt.getElectives(x,1);
        numofElectives=StudentExt.getElectivesnumber(x, 1);
        electivesLabel.setText("Select Electives : "+numofElectives+"      Use Ctrl to select more than one");
        int i=1;
        System.out.println(numofElectives);
        TextArea.setText("  Course Name\t\tCourse Code\t\tCredits\tCore/Elective\n");
        for(Course c:coreCoursesList)
        {
            String CourseName=c.getName();
            String CodeString=c.getCode();
            int credits=c.getCredit();
            TextArea.append(String.format("%10s",CourseName)+"\t\t"+CodeString+"\t\t"+credits+"\t"+"core\n");
            
            
        }
        for(Course c:electiveCoursesList)
        {
            String CourseName=c.getName();
            String CodeString=c.getCode();
            int credits=c.getCredit();
//            jList1.add(CourseName+"\t\t"+CodeString+"\t\t"+credits+"\t"+"elective\n");
//            listModel.addElement(String.format("%30s",CourseName)+"(  "+String.format("%s",CodeString)+"  )");
            listModel.addElement(c);
            
        }
        
        
    }//GEN-LAST:event_formComponentShown

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        
        if(jList.getSelectedIndices().length!=numofElectives)
        {
            JOptionPane.showMessageDialog(null,"Please Select the desired number of Electives" );
        }
        else
        {
            List<Course> l=jList.getSelectedValuesList();
            String result=StudentExt.semreg(RegisterPanel.loggedinStudent,l);
            JOptionPane.showMessageDialog(this, result);
             JPanel parent=(JPanel) this.getParent();
            CardLayout cl = (CardLayout)(parent.getLayout());
            cl.show(parent, s.STUDENT_LOGGEDINPANEL);
        }
        
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JPanel parent=(JPanel) this.getParent();
            CardLayout cl = (CardLayout)(parent.getLayout());
            cl.show(parent, s.STUDENT_LOGGEDINPANEL);
    }//GEN-LAST:event_jButton2ActionPerformed


    
    
    MouseListener mouseListener = new MouseAdapter() {
    public void mouseClicked(MouseEvent e) {
        


           if(jList.getSelectedIndices().length>numofElectives)
           {
               JOptionPane.showMessageDialog(null,"You can't select more  electives than you are permiited to" );
               jList.clearSelection();
           }
           
    }
};
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListPanel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JLabel electivesLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
