package erp;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ScrollPaneLayout;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prudhvi
 */
public class StudentGradeShowPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentGradeShowPanel
     */
    
    JTable table1;
    TabelModel model;
    public StudentGradeShowPanel() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleBar = new javax.swing.JLabel();
        ScrollPanel = new javax.swing.JScrollPane();
        GpaBar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CongoBox = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        TitleBar.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        TitleBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleBar.setText("Title bar");

        GpaBar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        GpaBar.setText("Gpa:");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CongoBox.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        CongoBox.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(TitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(CongoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GpaBar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(392, 392, 392))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(TitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GpaBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CongoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        JPanel parent=(JPanel) this.getParent();
        CardLayout cl = (CardLayout)(parent.getLayout());
        cl.show(parent, s.STUDENT_LOGGEDINPANEL);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
      
//        ScrollPanel.removeAll();
        List<Gradesheet> list=s.em.createQuery("SELECT g FROM Gradesheet g WHERE g.rollNo=:roll ORDER BY g.coursecode").
                setParameter("roll", RegisterPanel.loggedinStudent).getResultList();
        TitleBar.setText(RegisterPanel.loggedinStudent.getName()+"'s  Gradesheet");
         model=new TabelModel();
         table1=new JTable(model);
        ScrollPanel.getViewport().add(table1);
        table1.setVisible(true);
        table1.setFont(table1.getFont().deriveFont(20.0f));
        table1.setRowHeight(40);
        Gradesheet prev=null;
        double gpa=0,cgpa=0;
        int tcredits=0;
        int i=0;
        int overallcredits=0;
        int count=0;
        for(Gradesheet gs:list)
        {
            System.out.println(gs.getCoursecode().getCode().charAt(2));
            if( prev==null||prev.getCoursecode().getCode().charAt(2)==gs.getCoursecode().getCode().charAt(2) )
            {
                count++;
                model.setValueAt(gs.getCoursecode().getName(),i, 0);
                model.setValueAt(gs.getCoursecode().getCredit(),i, 1);
                model.setValueAt(giveGrade(gs.getGrade()),i, 2);
                gpa+=gs.getGrade()*gs.getCoursecode().getCredit();
                tcredits+=gs.getCoursecode().getCredit();
            }
            else
            {
                gpa/=tcredits;
                model.setValueAt("GPA for this semester",i, 1);
                model.setValueAt(""+gpa,i, 2);
                cgpa+=gpa*tcredits;
                overallcredits+=tcredits;
                gpa=0;
                tcredits=0;
                
                i++;
                 model.setValueAt(gs.getCoursecode().getName(),i, 0);
                model.setValueAt(gs.getCoursecode().getCredit(),i, 1);
                model.setValueAt(giveGrade(gs.getGrade()),i, 2);
                gpa+=gs.getGrade()*gs.getCoursecode().getCredit();
                tcredits+=gs.getCoursecode().getCredit();
                count=1;
            }
            
            prev=gs;
            i++;
        }
        if(count!=0)
        {
             gpa/=tcredits;
                model.setValueAt("GPA for this semester",i, 1);
                model.setValueAt(""+gpa,i, 2);
                cgpa+=gpa*tcredits;
                overallcredits+=tcredits;
        }
        cgpa/=overallcredits;
        CongoBox.setText("");
        if(cgpa<6)
            GpaBar.setBackground(Color.red);
        else if(cgpa>9)
        {GpaBar.setBackground(Color.green);CongoBox.setText("Congratulations");}
        GpaBar.setOpaque(true);
        GpaBar.setText("CGPA: "+String.format("%.2f", cgpa));
        
    }//GEN-LAST:event_formComponentShown
    class TabelModel extends AbstractTableModel
    {

    public String[] colNames={"Course Name","Credits","Grade"};
    public Object[][]data=new Object[100][3];

        
        
    
    
    @Override
    public int getRowCount() {
        
        return data.length;
       
    }

    @Override
    public int getColumnCount() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        return colNames.length;
    }

    @Override
    public Object getValueAt(int i, int i1) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        return data[i][i1];
    }
    @Override
    public String getColumnName(int index) {
        return colNames[index];
    }
    
    
    @Override
    public void setValueAt(Object value, int row, int col) {
        
            data[row][col]=value;
            fireTableCellUpdated(row, col);
        
        }

       
    }
    private String giveGrade(int credits)
    {
        
        char x = 0;
        switch(credits)
        {
            case 10:return "EX";
                
            case 9:x='A';
                break;
            case 8:x='B';
                break;
            case 7:x='C';
                    break;
            case 6:x='D';
                break;
            
            case 5:x='P';
                break;
            case 0:x='F';
                break;
                
        }
        return ""+x;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CongoBox;
    private javax.swing.JLabel GpaBar;
    private javax.swing.JScrollPane ScrollPanel;
    private javax.swing.JLabel TitleBar;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}

